.TH MECONIUM 6 "May 2025" "Version 0.1.0" "Games Manual"
.SH NAME
meconium \- a 2D platformer game built with SDL2
.SH SYNOPSIS
.B meconium
[\fIOPTIONS\fR]
.SH DESCRIPTION
\fBMeconium\fR is a 2D platformer game featuring pixel-art graphics, animation, and simple enemy AI. It is built using C++ and SDL2.

The player can run, jump, and interact with various in-game elements while navigating levels filled with enemies and hazards.

.SH OPTIONS
Currently, \fBmeconium\fR does not accept any command-line options.

.SH FILES
.TP
.I /usr/local/share/meconium/assets
Default location for game assets.

.SH AUTHOR
Zack Bartel <zack@bartel.com>

.SH COPYRIGHT
Copyright (C) 2025 Zack Bartel.  
Licensed under the MIT License.

.SH SEE ALSO
.BR sdl2 (7),
.BR sdl2_image (7),
.BR sdl2_mixer (7),
.BR sdl2_ttf (7)

